import { StyleSheet } from "react-native";
import type { AppColors } from "../lib/theme/types";

export function createQuickSaleStyles(c: AppColors) {
  return StyleSheet.create({
    flex: { flex: 1, backgroundColor: c.background },
    listContent: { paddingHorizontal: 16, paddingTop: 12 },
    headerBlock: { paddingBottom: 8 },
    sectionTitle: { fontSize: 17, fontWeight: "700", color: c.text },
    subSection: { marginTop: 14, marginBottom: 8, fontSize: 13, fontWeight: "600", color: c.textSecondary },
    hint: { marginTop: 4, marginBottom: 10, fontSize: 12, color: c.textSecondary },
    hScroll: { marginBottom: 4 },
    pill: {
      paddingHorizontal: 14,
      paddingVertical: 9,
      borderRadius: 20,
      backgroundColor: c.pill,
      marginRight: 8,
      marginBottom: 8,
    },
    pillActive: { backgroundColor: c.pillActive },
    pillOutline: {
      backgroundColor: c.surface,
      borderWidth: 1.5,
      borderColor: c.primary,
    },
    pillText: { color: c.pillText, fontSize: 14, fontWeight: "500" },
    pillTextActive: { color: c.pillTextActive, fontWeight: "700" },
    cartSection: {
      marginTop: 14,
      padding: 12,
      backgroundColor: c.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      gap: 10,
    },
    cartRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 10,
      paddingVertical: 8,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    cartMain: { flex: 1 },
    cartName: { fontSize: 15, fontWeight: "600", color: c.text },
    cartMeta: { marginTop: 4, fontSize: 12, color: c.textSecondary },
    cartActions: { alignItems: "flex-end", gap: 8 },
    qtyRow: { flexDirection: "row", alignItems: "center", gap: 10 },
    iconBtn: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: c.surfaceMuted,
      alignItems: "center",
      justifyContent: "center",
    },
    qtyTxt: { fontSize: 16, fontWeight: "700", color: c.text, minWidth: 22, textAlign: "center" },
    discBtn: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      backgroundColor: c.warningSurface,
      borderWidth: 1,
      borderColor: c.warning,
    },
    discBtnTxt: { fontSize: 12, fontWeight: "700", color: c.warning },
    cartTotal: { marginTop: 4, fontSize: 17, fontWeight: "800", color: c.success, textAlign: "right" },
    searchRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: c.searchBackground,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.inputBorder,
      paddingLeft: 10,
      marginTop: 8,
      overflow: "hidden",
    },
    searchIcon: { marginRight: 4 },
    searchInput: {
      flex: 1,
      borderWidth: 0,
      backgroundColor: "transparent",
      paddingVertical: 12,
    },
    scanBtn: {
      backgroundColor: c.primary,
      paddingHorizontal: 14,
      paddingVertical: 12,
      justifyContent: "center",
      alignItems: "center",
    },
    scanWarn: { color: c.warning, marginTop: 8, fontSize: 13 },
    microHint: { marginTop: 8, fontSize: 11, color: c.textSecondary, lineHeight: 15 },
    warn: { paddingVertical: 24, color: c.warning, textAlign: "center" },
    footer: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: c.footerBackdrop,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
    },
    errFoot: { color: c.danger, marginBottom: 8, textAlign: "center", fontSize: 13 },
    creditLinkBtn: {
      alignSelf: "flex-start",
      marginTop: 6,
      marginBottom: 6,
      paddingVertical: 6,
      paddingHorizontal: 2,
    },
    creditLinkTxt: { fontSize: 13, fontWeight: "700", color: c.link, textDecorationLine: "underline" },
    creditBanner: {
      marginTop: 6,
      padding: 12,
      borderRadius: 12,
      borderWidth: 1,
      marginBottom: 8,
    },
    creditBannerWarn: { backgroundColor: c.warningSurface, borderColor: c.warning },
    creditBannerDanger: { backgroundColor: c.dangerSurface, borderColor: c.danger },
    creditBannerTitle: { fontSize: 14, fontWeight: "800", color: c.text, marginBottom: 6 },
    creditBannerTxt: { fontSize: 12, color: c.textSecondary, marginBottom: 4 },
    creditBannerBold: { marginTop: 8, fontSize: 13, fontWeight: "800", color: c.danger },
    finalBtn: {
      backgroundColor: c.primary,
      paddingVertical: 15,
      borderRadius: 12,
      alignItems: "center",
    },
    finalBtnDis: { opacity: 0.45 },
    finalInner: { flexDirection: "row", alignItems: "center", gap: 10 },
    finalTxt: { color: c.primaryForeground, fontWeight: "800", fontSize: 17 },
  });
}
