packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true

supportedArchitectures:
  os:
    - current
  cpu:
    - current

overrides:
  react: 19.2.6
  react-dom: 19.2.6
  "@prisma/client": 7.8.0
  "@prisma/adapter-pg": 7.8.0
  prisma: 7.8.0

nodeLinker: hoisted
