/** Schemas demo para categorias – cadastro estilo PIM (campos dinâmicos por tipo de produto). */

export const CATEGORY_SCHEMA_BY_CODE = {
  GENERAL: [
    { key: "brand", label: "Marca", type: "text", section: "Identidade", placeholder: "Fabricante ou marca própria" },
    {
      key: "gtin",
      label: "GTIN/EAN",
      type: "text",
      section: "Identidade",
      placeholder: "789…",
    },
    {
      key: "ncm",
      label: "NCM",
      type: "text",
      section: "Fiscal",
      placeholder: "ex.: 27101932",
    },
    {
      key: "origin_country",
      label: "País de origem",
      type: "text",
      section: "Origem",
      placeholder: "BR",
    },
  ],
  CONSUMABLE: [
    {
      key: "sale_unit",
      label: "Unidade de venda",
      type: "select",
      required: true,
      section: "Embalagem",
      options: [
        { value: "UN", label: "Unidade" },
        { value: "CX", label: "Caixa" },
        { value: "FD", label: "Fardo" },
      ],
    },
    {
      key: "net_content",
      label: "Conteúdo líquido / quantidade",
      type: "text",
      section: "Embalagem",
      placeholder: "ex.: 500 ml ou 1 kg",
    },
    {
      key: "batch_traceability",
      label: "Exige rastreabilidade de lote",
      type: "boolean",
      section: "Qualidade",
    },
  ],
  FOOD: [
    {
      key: "allergens",
      label: "Alérgenos / advertências",
      type: "textarea",
      section: "Segurança alimentar",
      placeholder: "Contém glúten, leite…",
    },
    {
      key: "storage_instructions",
      label: "Armazenamento",
      type: "textarea",
      section: "Logística",
      placeholder: "Manter refrigerado, temperatura ambiente…",
    },
    {
      key: "portion_description",
      label: "Porção / rendimento",
      type: "text",
      section: "Informação ao consumidor",
      placeholder: "ex.: 30 g ou ~15 unidades",
    },
    {
      key: "organic_certified",
      label: "Produto orgânico certificado",
      type: "boolean",
      section: "Certificações",
    },
  ],
  /** Categoria dedicada no seed — produtos alimentícios para varejo / distribuição. */
  ALIMENTICIOS: [
    {
      key: "food_segment",
      label: "Segmento",
      type: "select",
      required: true,
      section: "Classificação",
      options: [
        { value: "PERECIVEL", label: "Perecível (refrigerado/congelado)" },
        { value: "NAO_PERECIVEL", label: "Não perecível" },
        { value: "BEBIDA", label: "Bebidas" },
        { value: "CONGELADO", label: "Congelados" },
      ],
    },
    {
      key: "brand",
      label: "Marca",
      type: "text",
      section: "Identidade",
      placeholder: "Marca no rótulo",
    },
    {
      key: "gtin",
      label: "GTIN/EAN",
      type: "text",
      section: "Identidade",
      placeholder: "789…",
    },
    {
      key: "allergens",
      label: "Alérgenos / advertências",
      type: "textarea",
      section: "Segurança alimentar",
      placeholder: "Contém glúten, leite…",
    },
    {
      key: "storage_instructions",
      label: "Armazenamento",
      type: "textarea",
      section: "Logística",
      placeholder: "Temperatura máx./mín., após aberto…",
    },
    {
      key: "net_weight_volume",
      label: "Peso líquido / volume",
      type: "text",
      section: "Embalagem",
      placeholder: "ex.: 400 g ou 1 L",
    },
    {
      key: "batch_traceability",
      label: "Exige rastreabilidade de lote",
      type: "boolean",
      section: "Qualidade",
    },
    {
      key: "organic_certified",
      label: "Orgânico certificado",
      type: "boolean",
      section: "Certificações",
    },
  ],
  HYGIENE: [
    {
      key: "hygiene_category",
      label: "Tipo de produto",
      type: "select",
      required: true,
      section: "Classificação",
      options: [
        { value: "BODY", label: "Corpo / banho" },
        { value: "HAIR", label: "Cabelo" },
        { value: "ORAL", label: "Higiene bucal" },
        { value: "HAND", label: "Mãos / antisépticos" },
        { value: "HOME", label: "Limpeza doméstica / superfícies" },
      ],
    },
    {
      key: "brand",
      label: "Marca",
      type: "text",
      section: "Identidade",
    },
    {
      key: "volume_ml_or_g",
      label: "Volume / peso da embalagem",
      type: "text",
      section: "Embalagem",
      placeholder: "ex.: 400 ml ou 90 g",
    },
    {
      key: "usage_instructions",
      label: "Modo de uso / advertências",
      type: "textarea",
      section: "Informação ao consumidor",
      placeholder: "Uso externo, não ingerir…",
    },
    {
      key: "dermatologically_tested",
      label: "Testado dermatologicamente",
      type: "boolean",
      section: "Claims",
    },
    {
      key: "ph_claim",
      label: "pH declarado (opcional)",
      type: "text",
      section: "Especificações",
      placeholder: "ex.: pH 5,5",
    },
    {
      key: "child_safe_cap",
      label: "Tampa trava infantil (child-resistant)",
      type: "boolean",
      section: "Segurança",
    },
  ],
  AUTOMOTIVE: [
    {
      key: "automotive_line",
      label: "Linha / família",
      type: "select",
      required: true,
      section: "Automotivo",
      options: [
        { value: "OIL_FLUID", label: "Óleos e fluidos" },
        { value: "SUSPENSION", label: "Suspensão" },
        { value: "FILTERS", label: "Filtros" },
        { value: "BRAKES", label: "Freios" },
        { value: "ELECTRICAL", label: "Elétrica / ignição" },
        { value: "BODY", label: "Carroceria / acabamento" },
      ],
    },
    {
      key: "oem_reference",
      label: "Referência OEM / equivalente",
      type: "text",
      section: "Automotivo",
      placeholder: "Código original ou cross-reference",
    },
    {
      key: "viscosity_sae",
      label: "Viscosidade SAE (óleos)",
      type: "text",
      section: "Especificações",
      placeholder: "ex.: 5W30 — use quando aplicável",
    },
    {
      key: "vehicle_application_notes",
      label: "Compatibilidade veículos",
      type: "textarea",
      section: "Aplicação",
      placeholder: "Modelos, anos, motorização…",
    },
  ],
} as const;
